# NumPy Library


NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays


## Use case

Calculate mean


In [1]:
number_list = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

sum_num = 0
n = len(number_list)

for num in number_list:
    sum_num = sum_num + num

result = sum_num / n
print(result)


5.5


In [2]:
import numpy as np

np.mean(number_list)


5.5

## Importing

To use Numpy, we first need to import the `numpy` package:


In [3]:
import numpy as np


## Array creation

NumPy is used to work with arrays. The array object in NumPy is called <code>ndarray</code>.


## <code>array()</code> function


In [4]:
# Create an array 1x3 Dimension from Python list
a = np.array([1, 2, 3])
print(a)


[1 2 3]


In [5]:
type(a)


numpy.ndarray

In [6]:
print(a.shape)
print(np.shape(a))


(3,)
(3,)


In [7]:
# Create an array 2x3 Dimension from Python list
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)


[[1 2 3]
 [4 5 6]]


In [8]:
print(b.shape)
print(np.shape(b))


(2, 3)
(2, 3)


- <a href=https://miro.medium.com/max/2000/1*Ikn1J6siiiCSk4ivYUhdgw.png>หน้าตาของ array แต่ละมิติ</a>
- credit: https://medium.com/datadriveninvestor/artificial-intelligence-series-part-2-numpy-walkthrough-64461f26af4f


### NumPy array VS Python list


In [9]:
a_list = [1, 2, 3]
b_list = [4, 5, 6]
print(a_list + b_list)



[1, 2, 3, 4, 5, 6]


In [10]:
a_np = np.array([1, 2, 3])
b_np = np.array([4, 5, 6])
print(a_np + b_np)


[5 7 9]


In [11]:
print(a_np + a_list)



[2 4 6]


In [12]:
a_list = [1, 2, 3]
c_np = np.array([[1, 2, 3], [4, 5, 6]])
print(a_list)
print("---")
print(c_np)
print("---")
print(c_np + a_list)



[1, 2, 3]
---
[[1 2 3]
 [4 5 6]]
---
[[2 4 6]
 [5 7 9]]


### Others functions to create NumPy arrays


In [13]:
# Create an array of all zeros
a = np.zeros((3, 3))
print(a)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [14]:
# Create an array of all ones
b = np.ones((2, 3))
print(b)


[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
# Create a constant array
c = np.full((5, 5), 10)
print(c)


[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


In [16]:
c = np.ones((5, 5)) * 3
print(c)


[[3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]
 [3. 3. 3. 3. 3.]]


In [17]:
# Create a 5x5 identity matrix
d = np.eye(5)
print(d)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [18]:
# Create an array filled with random values
e1 = np.random.random((4, 4))
e2 = np.random.random((4, 4))
print(e1)
print("---")
print(e2)


[[0.11676549 0.09477664 0.8160338  0.39572915]
 [0.84370681 0.74449886 0.43449166 0.09525286]
 [0.28272134 0.68669368 0.7163538  0.5887373 ]
 [0.91024839 0.22081562 0.11545947 0.86983404]]
---
[[0.34126173 0.23524395 0.79125858 0.82667401]
 [0.35480564 0.66494889 0.43086459 0.45513586]
 [0.23184758 0.8703362  0.51780323 0.36145364]
 [0.92734019 0.8341442  0.94045897 0.42925289]]


In [19]:
np.random.seed(0)
e1 = np.random.random((4, 4))
np.random.seed(0)
e2 = np.random.random((4, 4))
print(e1)
print("---")
print(e2)


[[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]]
---
[[0.5488135  0.71518937 0.60276338 0.54488318]
 [0.4236548  0.64589411 0.43758721 0.891773  ]
 [0.96366276 0.38344152 0.79172504 0.52889492]
 [0.56804456 0.92559664 0.07103606 0.0871293 ]]


In [20]:
np.random.seed(1)
e = np.random.random((4, 4))
print(e)


[[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01]
 [3.96767474e-01 5.38816734e-01 4.19194514e-01 6.85219500e-01]
 [2.04452250e-01 8.78117436e-01 2.73875932e-02 6.70467510e-01]]


In [21]:
np.random.seed(1)
e = np.random.random((4, 4))
print(e)


[[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01]
 [3.96767474e-01 5.38816734e-01 4.19194514e-01 6.85219500e-01]
 [2.04452250e-01 8.78117436e-01 2.73875932e-02 6.70467510e-01]]


In [22]:
# Create an array from a number range
f = np.arange(start=1, stop=10, step=2)  # Stop(excluding from range)
print(f)


[1 3 5 7 9]


# Array indexing


In [23]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [24]:
print(a[0])
print(a[1][1])


[1 2 3 4]
6


# Array slicing

Similar to Python lists, numpy arrays can be sliced. Since arrays may be multidimensional, you must specify a slice for each dimension of the array.

```python
array[start_row : stop_row (exclude), start_column : stop_column(exclude), ...]
```


In [25]:
print(a[0:2, 0:2])
print("---")
print(a[1:, 2:])
print("---")
print(a[:2, 1:3])



[[1 2]
 [5 6]]
---
[[ 7  8]
 [11 12]]
---
[[2 3]
 [6 7]]


## View concept

A slice of an array is a view into the same data, so modifying it will modify the original array.


In [26]:
print(a)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [27]:
b = a[1:, 1:]
print(b[0, 0])
print(a[1, 1])


6
6


In [28]:
b[0, 0] = 70



In [29]:
print(b)
print("---")
print(a)


[[70  7  8]
 [10 11 12]]
---
[[ 1  2  3  4]
 [ 5 70  7  8]
 [ 9 10 11 12]]


# Boolean array indexing

Boolean array indexing lets you pick out arbitrary elements of an array. Frequently this type of indexing is used to select the elements of an array that satisfy some condition. Here is an example:


In [30]:
a = np.array([[1, 2], [3, 4], [5, 6]])
print(a)


[[1 2]
 [3 4]
 [5 6]]


In [31]:
# Find the elements of a that are bigger than 2;
bool_idx = a > 2
print(bool_idx)


[[False False]
 [ True  True]
 [ True  True]]


In [32]:
# We use boolean array indexing to construct a rank 1 array
# consisting of the elements of a corresponding to the True values
# of bool_idx
print(a[bool_idx])


[3 4 5 6]


In [33]:
# We can do all of the above in a single concise statement:
print(a[a > 2])



[3 4 5 6]


## Reshaping array


In [34]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a.shape)
print(a)


(3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [35]:
print(a.reshape(2, 6))
print(a.reshape(2, 6).shape)



[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


In [36]:
print(a[a > 2].reshape(2, 5))



[[ 3  4  5  6  7]
 [ 8  9 10 11 12]]


In [37]:
# One shape dimension can be -1. In this case,
# the value is inferred from the length of the array and remaining dimensions.
print(a.reshape(-1, 3))



[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Datatypes


Every numpy array is a grid of elements of the same type. Numpy provides a large set of numeric datatypes that you can use to construct arrays. Numpy tries to guess a datatype when you create an array, but functions that construct arrays usually also include an optional argument to explicitly specify the datatype. You can read all about numpy datatypes in the documentation [link1](http://docs.scipy.org/doc/numpy/reference/arrays.dtypes.html) or [link2.](https://docs.scipy.org/doc/numpy-1.10.1/user/basics.types.html)


In [38]:
x = np.array([1, 2])  # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)  # Force a particular datatype
o = np.array([1, "1", "1.2"])

print(x.dtype)
print(y.dtype)
print(z.dtype)
print(o.dtype)


int32
float64
int64
<U11


# Array math

Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:


In [39]:
x = np.array([[3, 3], [3, 3]], dtype=np.float64)
y = np.array([[2, 2], [2, 2]], dtype=np.float64)
print(x)
print(y)


[[3. 3.]
 [3. 3.]]
[[2. 2.]
 [2. 2.]]


In [52]:
# Elementwise operation
print(x + y)
print("---")
print(x - y)
print("---")
print(x * y)
print("---")
print(x / y)


[[ 6  8]
 [10 12]]
---
[[-4 -4]
 [-4 -4]]
---
[[ 5 12]
 [21 32]]
---
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [41]:
# Elementwise operation
print(np.add(x, y))
print("---")
print(np.subtract(x, y))
print("---")
print(np.multiply(x, y))
print("---")
print(np.divide(x, y))


[[5. 5.]
 [5. 5.]]
---
[[1. 1.]
 [1. 1.]]
---
[[6. 6.]
 [6. 6.]]
---
[[1.5 1.5]
 [1.5 1.5]]


In [42]:
# Inner product of vectors
v = np.array([1, 2])
w = np.array([10, 20])

# (1*10)+(2*20) = 50
print(np.dot(v, w))
print(v.dot(w))
print(v @ w)


50
50
50


In [55]:
# Matrix / matrix product; both produce the rank 2 array
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
print(np.dot(x, y))
print(np.matmul(x,y))
print(x @ y)

[[19 22]
 [43 50]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


# Arrays functions


In [44]:
x = np.array([[1, 2], [3, 4]])
print(x)


[[1 2]
 [3 4]]


In [45]:
# Compute sum of all elements
print(x.sum())


10


In [46]:
# Compute sum of each column
print(x.sum(axis=0))


[4 6]


In [47]:
# Compute sum of each row
print(x.sum(axis=1))


[3 7]


In [48]:
print(np.sum(x, axis=1))


[3 7]


In [49]:
print(x.mean())


2.5


In [50]:
print(x.max())


4


In [51]:
print(x.min())


1
