# NumPy Excercises

# Ex 1.
จงสร้าง numpy array ขนาด 1 มิติ ที่มีแต่เลขคู่ ที่มีค่าอยู่ในช่วง 0 - 100

In [1]:
import numpy as np
a = np.arange(start=0, stop = 101, step = 2)
print(a)

[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]


# Ex 2.
จงสร้าง array ขนาด 2 มิติ ขนาด 5 x 5 โดยแต่ละค่าจะเป็นค่า random ที่มีการตั้ง seed(0)

In [2]:
np.random.seed(0)
a = np.random.random((5,5))
print(a)

[[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]
 [0.64589411 0.43758721 0.891773   0.96366276 0.38344152]
 [0.79172504 0.52889492 0.56804456 0.92559664 0.07103606]
 [0.0871293  0.0202184  0.83261985 0.77815675 0.87001215]
 [0.97861834 0.79915856 0.46147936 0.78052918 0.11827443]]


# Ex 3.
จงหาค่าผลรวมของ array ที่สร้างจากข้อ 2

In [3]:
print(np.sum(a))

14.769156361309756


# Ex 4.
จงหาค่าผลรวมของ array เฉพาะแกน axis ที่ 0 ที่สร้างจากข้อ 2

In [4]:
print(np.sum(a, axis=0))

[3.0521803  2.50104846 3.35668015 3.99282851 1.86641895]
